# Configuration Settings for ZED-F9P device
debug: 1                 # Range 0-4 (0 means no debug statements will print)

device: /dev/ttyACM0     # ZED-F9P rover serial port
#device: tcp://127.0.0.1:2000
frame_id: gps
rate: 5                     # in Hz
nav_rate: 1                 # [# of measurement cycles], recommended 1 Hz, may 
                            # be either 5 Hz (Dual constellation) or 
                            # 8 Hz (GPS only)

#fix_mode: auto

config_on_startup: false # use chip config

uart1:
  baudrate: 230400 #115200       # serial port baudrate
  in: 32
  out: 3

gnss:
  gps: true
  sbas: true #false
  qzss: true #false
  glonass: true
  beidou: true
  galileo: true

# Enable u-blox message publishers
publish:
  all: false
  nav:
    all: true
    relposned: true
    posllh: true
    posecef: true

